name: Java CI with Maven

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: 'GOFO Implementation'
    
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn compile
        working-directory: 'GOFO Implementation'

      - name: Run Unit Tests with Maven
        run: |
          mvn test -Dtest=AdministratorTest test;
          mvn test -Dtest=PlayGroundScheduleTest test;
          mvn test -Dtest=PlayerTest test;
          mvn test -Dtest=PlaygroundOwnerTest test;
          mvn test -Dtest=PlaygroundTest test;
          mvn test -Dtest=eWalletTest test;
          mvn test -Dtest=userProfileTest test;
          EXIT_CODE=$?
        working-directory: 'GOFO Implementation'

      - name: Run Use Cases Tests with Maven
        run: mvn test -Dtest=CSU01Test test;
        if: always()
        working-directory: 'GOFO Implementation'
