name: Java CI with Maven

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: 'GOFO Implementation'
    
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
             mvn clean compile --file 'GOFO Implementation/pom.xml'
        working-directory: 'GOFO Implementation'

      - name: Run Unit Tests with Maven
        run: |
          mvn test -Dtest=AdministratorTest test --file 'GOFO Implementation/pom.xml';
          mvn test -Dtest=PlayGroundScheduleTest test --file 'GOFO Implementation/pom.xml';
          mvn test -Dtest=PlayerTest test --file 'GOFO Implementation/pom.xml';
          mvn test -Dtest=PlaygroundOwnerTest test --file 'GOFO Implementation/pom.xml';
          mvn test -Dtest=PlaygroundTest test --file 'GOFO Implementation/pom.xml';
          mvn test -Dtest=eWalletTest test --file 'GOFO Implementation/pom.xml';
          mvn test -Dtest=userProfileTest test --file 'GOFO Implementation/pom.xml';
          EXIT_CODE=$?
        working-directory: 'GOFO Implementation'

      - name: Run Use Case 01 with Maven
        run: |
          mvn test -Dtest=CSU01Test test --file 'GOFO Implementation/pom.xml';
          EXIT_CODE=$?
        working-directory: 'GOFO Implementation'

      - name: Run Use Case 02 with Maven
        run: |
          mvn test -Dtest=CSU02Test test --file 'GOFO Implementation/pom.xml';
          EXIT_CODE=$?
        working-directory: 'GOFO Implementation'  

      - name: Run Use Case 03 with Maven
        run: |
          mvn test -Dtest=CSU03Test test --file 'GOFO Implementation/pom.xml';
          EXIT_CODE=$?
        working-directory: 'GOFO Implementation'  

      - name: Run Use Case 04 with Maven
        run: |
            mvn test -Dtest=CSU04Test test --file 'GOFO Implementation/pom.xml';
            EXIT_CODE=$?
        working-directory: 'GOFO Implementation'  

        
      - name: Run Use Case 05 with Maven
        run: |
          mvn test -Dtest=CSU05Test test --file 'GOFO Implementation/pom.xml';
          EXIT_CODE=$?
        working-directory: 'GOFO Implementation'  

      
      - name: Run Use Case 06 with Maven
        run: |
          mvn test -Dtest=CSU06Test test --file 'GOFO Implementation/pom.xml';
          EXIT_CODE=$?
        working-directory: 'GOFO Implementation'  

        
      - name: Run Use Case 07 with Maven
        run: |
          mvn test -Dtest=CSU07Test test --file 'GOFO Implementation/pom.xml';
          EXIT_CODE=$?
        working-directory: 'GOFO Implementation'  

      
      - name: Run Use Case 08 with Maven
        run: |
          mvn test -Dtest=CSU08Test test --file 'GOFO Implementation/pom.xml';
          EXIT_CODE=$?
        working-directory: 'GOFO Implementation'  